version: 2
updates:
  # Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "gomod"
    directory: "/cmd/controller"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/cmd/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/cmd/fortuna"
    schedule:
      interval: "weekly"

  # Docker
  - package-ecosystem: "docker"
    directory: "/cmd/controller"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/api"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/cmd/fortuna"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"