version: 2

run:
  timeout: 5m
  tests: true
  go: '1.24'

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - misspell
    - gocritic
    - revive

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false
    exclude-functions:
      - (io.Closer).Close
      - (io.ReadCloser).Close

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gosec:
    config:
      G115: false
      G301: false

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true
      - name: var-naming
        disabled: true
      - name: unused-parameter
        disabled: true

  staticcheck:
    checks:
      - "all"
      - "-ST1005"

issues:
  exclude-dirs:
    - vendor
    - tmp
    - pkg/api/docs
    - tests

  exclude-rules:
    # Disable revive for test files (unit tests in packages)
    - path: _test\.go
      linters:
        - revive

    # Disable errcheck and gosec in test files (unit tests in packages)
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Exclude fieldalignment in non-test code
    - linters:
        - govet
      text: "fieldalignment"

    # Allow intentionally ignored errors with blank identifier
    - linters:
        - errcheck
      source: "^\\s*_\\s*=\\s*"

    # Allow nolint directives
    - linters:
        - errcheck
      source: "//nolint:errcheck"

    # Allow deferred Close without error check
    - linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"
      source: "defer.*\\.Close\\(\\)"

    # Ignore G115 integer overflow warnings
    - linters:
        - gosec
      text: "G115:"

    # Ignore G301 file permissions
    - linters:
        - gosec
      text: "G301:"

    # Allow QF1003 (tagged switch suggestions)
    - linters:
        - staticcheck
      text: "QF1003:"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    stdout:
      format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
