run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Standard Go vet
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis
    - unused        # Check for unused code
    - gosec         # Security issues
    - misspell      # Spelling errors
    - gofmt         # Code formatting
    - gocritic      # Go code review
    - revive        # Fast, configurable, extensible, flexible linter
    - typecheck     # Type checking

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: false
    # Use exclude-functions instead of deprecated ignore
    exclude-functions:
      - (io.Closer).Close
      - (io.ReadCloser).Close

  govet:
    enable-all: true
    disable:
      - shadow
      - fieldalignment  # Disable fieldalignment entirely - it's overly strict

  gosec:
    excludes:
      - G115  # We've handled these with #nosec where appropriate

  revive:
    rules:
      - name: exported
        disabled: true

  unused:
    # Only report exported unused items
    check-exported: false
    # Treat field-only usage as usage (fixes false positives for mutex fields)
    field-writes-are-uses: true

issues:
  exclude-dirs:
    - vendor
    - tmp
    - pkg/api/docs  # Exclude swagger generated code

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Exclude fieldalignment warnings (treat as info only)
    - linters:
        - govet
      text: "fieldalignment"

    # Allow blank identifier assignments for intentionally ignored errors
    - linters:
        - errcheck
      text: "Error return value of.*is not checked"
      source: "^\\s*_\\s*=\\s*"

    # Allow nolint directives for errcheck
    - linters:
        - errcheck
      source: "//nolint:errcheck"

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true